import Link from "next/link";
import type { LeadStage } from "@prisma/client";
import { AdminShell } from "@/components/admin/admin-shell";
import { requireAdmin } from "@/lib/admin/auth";
import { LEAD_STAGE_LABELS } from "@/lib/constants";
import { prisma } from "@/lib/db";
import { redactMobile } from "@/lib/utils";

export const dynamic = "force-dynamic";
export default async function AdminLeadsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const { admin } = await requireAdmin(); const query = await searchParams; const search = query.search?.trim(); const stage = query.stage && Object.hasOwn(LEAD_STAGE_LABELS, query.stage) ? query.stage as LeadStage : undefined;
  const leads = await prisma.lead.findMany({ where: { deletedAt: null, ...(search ? { OR: [{ fullName: { contains: search, mode: "insensitive" } }, { mobile: { contains: search } }, { city: { contains: search, mode: "insensitive" } }] } : {}), ...(stage && LEAD_STAGE_LABELS[stage] ? { stage } : {}) }, orderBy: { createdAt: "desc" }, take: 100, include: { assessments: { orderBy: { createdAt: "desc" }, take: 1 }, orders: { orderBy: { createdAt: "desc" }, take: 1 } } });
  return <AdminShell title="Lead CRM" description="Search, filter and inspect verified profile requests." adminName={admin.fullName}><form className="mb-5 grid gap-3 rounded-2xl border border-line bg-white p-4 sm:grid-cols-[1fr_220px_auto]"><input name="search" defaultValue={search} placeholder="Name, mobile or city" className="min-h-11 rounded-xl border border-line px-4" /><select name="stage" defaultValue={stage || ""} className="min-h-11 rounded-xl border border-line px-3"><option value="">All stages</option>{Object.entries(LEAD_STAGE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="rounded-xl bg-navy-950 px-5 py-2 text-sm font-bold text-white">Apply filters</button></form><div className="overflow-x-auto rounded-2xl border border-line bg-white"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-surface text-xs text-slate-500"><tr><th className="px-5 py-4">Lead</th><th className="px-5 py-4">Location</th><th className="px-5 py-4">Stage</th><th className="px-5 py-4">Assessment</th><th className="px-5 py-4">Marketing</th><th className="px-5 py-4">Created</th></tr></thead><tbody className="divide-y divide-line">{leads.map((lead) => <tr key={lead.id} className="hover:bg-surface/60"><td className="px-5 py-4"><Link href={`/admin/leads/${lead.id}`} className="font-bold text-navy-950 hover:text-brand-700">{lead.fullName}</Link><p className="mt-1 text-xs text-slate-500">{redactMobile(lead.mobile)}</p></td><td className="px-5 py-4 text-slate-600">{[lead.city, lead.state].filter(Boolean).join(", ") || "—"}</td><td className="px-5 py-4"><span className="rounded-full bg-brand-100 px-2.5 py-1 text-xs font-bold text-brand-700">{LEAD_STAGE_LABELS[lead.stage]}</span></td><td className="px-5 py-4 text-slate-600">{lead.assessments[0]?.status ?? "Not started"}</td><td className="px-5 py-4 text-slate-600">{lead.marketingOptedOutAt ? "Opted out" : "Check consent"}</td><td className="px-5 py-4 text-slate-600">{lead.createdAt.toLocaleDateString("en-IN")}</td></tr>)}</tbody></table>{leads.length === 0 ? <p className="p-8 text-center text-sm text-slate-500">No leads match these filters.</p> : null}</div><div className="mt-5 flex justify-end"><a href="/api/admin/export/leads" className="rounded-xl border border-line bg-white px-4 py-2.5 text-sm font-bold text-navy-900">Authorized CSV export</a></div></AdminShell>;
}
