import type { Metadata } from "next";
import { CheckoutClient } from "@/components/checkout/checkout-client";
import { prisma } from "@/lib/db";
import { verifyAccessToken } from "@/lib/security/tokens";
import { formatInr } from "@/lib/utils";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Secure Checkout", robots: { index: false, follow: false } };

export default async function CheckoutPage({ searchParams }: { searchParams: Promise<{ product?: string; assessment?: string; token?: string }> }) { const query = await searchParams; if (!query.product || !query.assessment || !query.token) return <InvalidCheckout />; let token; try { token = await verifyAccessToken(query.token, "result_access"); } catch { return <InvalidCheckout />; } if (token.sub !== query.assessment) return <InvalidCheckout />; const [assessment, product] = await Promise.all([prisma.assessment.findUnique({ where: { id: query.assessment }, include: { lead: true } }), prisma.product.findUnique({ where: { slug: query.product } })]); if (!assessment || assessment.leadId !== token.leadId || !product?.active) return <InvalidCheckout />; const subtotal = Number(product.salePrice); const gst = Math.round(subtotal * Number(product.gstRate)) / 100; const total = Math.round((subtotal + gst) * 100) / 100; return <section className="min-h-screen bg-surface py-10 sm:py-16"><div className="page-shell"><div className="mx-auto max-w-5xl"><div className="mb-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-700">Secure checkout</p><h1 className="mt-2 text-3xl font-bold tracking-[-0.04em] text-navy-950">Review your report order</h1></div><CheckoutClient assessmentId={assessment.id} productSlug={product.slug} resultToken={query.token} productName={product.name} subtotal={formatInr(subtotal)} gst={formatInr(gst)} total={formatInr(total)} customerName={assessment.lead.fullName} customerMobile={assessment.lead.mobile} referralCode={assessment.referralCode ?? undefined} /></div></div></section>; }
function InvalidCheckout() { return <section className="min-h-[65vh] bg-surface py-20"><div className="page-shell"><div className="mx-auto max-w-lg rounded-3xl border border-line bg-white p-8 text-center"><h1 className="text-2xl font-bold text-navy-950">Secure checkout link required</h1><p className="mt-3 text-sm leading-7 text-slate-600">Open checkout from your free result so we can verify the product and assessment.</p></div></div></section>; }
