import type { Metadata } from "next";
import { CheckCircle2, Download, FileText, LockKeyhole } from "lucide-react";
import { prisma } from "@/lib/db";
import { verifyAccessToken } from "@/lib/security/tokens";
import { ButtonLink } from "@/components/ui/button";
import { ReportActions } from "@/components/report-actions";

export const dynamic = "force-dynamic"; export const metadata: Metadata = { title: "Secure Report", robots: { index: false, follow: false } };
export default async function ReportPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ token?: string }> }) { const { id } = await params; const { token } = await searchParams; if (!token) return <InvalidReport />; try { const payload = await verifyAccessToken(token, "report_access"); if (payload.sub !== id) throw new Error("mismatch"); } catch { return <InvalidReport />; } const report = await prisma.report.findUnique({ where: { id }, include: { lead: true, order: { include: { product: true } } } }); if (!report || report.order.status !== "PAID") return <InvalidReport />; if (report.status === "QUEUED") await prisma.report.update({ where: { id }, data: { status: "READY", generatedAt: new Date() } }); return <section className="min-h-[75vh] bg-surface py-16"><div className="page-shell"><div className="mx-auto max-w-2xl rounded-3xl border border-line bg-white p-7 shadow-soft sm:p-10"><div className="flex items-start justify-between gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-brand-100 text-brand-700"><FileText size={27} /></span><span className="rounded-full bg-brand-100 px-3 py-1.5 text-xs font-bold text-brand-700">Ready</span></div><h1 className="mt-7 text-3xl font-bold tracking-[-0.04em] text-navy-950">Your personalized report</h1><p className="mt-3 text-sm leading-7 text-slate-600">{report.order.product.name} for {report.lead.fullName}</p><div className="mt-6 rounded-2xl bg-surface p-5"><p className="text-xs font-semibold text-slate-500">Report reference</p><p className="mt-1 text-lg font-extrabold text-navy-950">{report.reportReference}</p></div><div className="mt-6 flex items-start gap-3 text-sm leading-7 text-slate-600"><LockKeyhole className="mt-1 shrink-0 text-brand-700" size={18} />This signed link expires. Do not forward a report containing your personal assessment.</div><a href={`/api/reports/${id}/download?token=${encodeURIComponent(token)}`} className="mt-7 flex min-h-14 w-full items-center justify-center gap-2 rounded-xl bg-brand-600 px-6 font-bold text-white hover:bg-brand-700"><Download size={18} />Download branded PDF</a><p className="mt-4 flex items-center justify-center gap-2 text-xs text-slate-500"><CheckCircle2 size={14} className="text-brand-600" />Hindi and English font subsets are embedded for mobile-safe rendering.</p><ReportActions reportId={id} token={token}/></div></div></section>; }
function InvalidReport() { return <section className="min-h-[65vh] bg-surface py-20"><div className="page-shell"><div className="mx-auto max-w-lg rounded-3xl border border-line bg-white p-8 text-center"><h1 className="text-2xl font-bold text-navy-950">Secure report access required</h1><p className="mt-3 text-sm leading-7 text-slate-600">This link is invalid, expired or not linked to a paid report.</p><ButtonLink href="/contact" variant="secondary" className="mt-6">Contact support</ButtonLink></div></div></section>; }
