"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, CircleAlert, Loader2, LockKeyhole, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PAYMENT_DESCRIPTION, PLATFORM_DISCLAIMER } from "@/lib/constants";
import { trackEvent } from "@/lib/analytics-client";

declare global { interface Window { Razorpay?: new (options: Record<string, unknown>) => { open: () => void; on: (event: string, callback: (response: { error?: { description?: string } }) => void) => void } } }

type Props = { assessmentId: string; productSlug: string; resultToken: string; productName: string; subtotal: string; gst: string; total: string; customerName: string; customerMobile: string; referralCode?: string };

export function CheckoutClient(props: Props) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function pay() { setBusy(true); setError(""); trackEvent("checkout_opened", { product: props.productSlug }); try { const orderResponse = await fetch("/api/payments/create-order", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ assessmentId: props.assessmentId, productSlug: props.productSlug, resultToken: props.resultToken, referralCode: props.referralCode }) }); const order = await orderResponse.json(); if (!orderResponse.ok) throw new Error(order.error || "Unable to create order."); if (order.provider === "mock") { const response = await fetch("/api/payments/mock-complete", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ internalOrderId: order.internalOrderId, resultToken: props.resultToken }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Mock payment failed."); trackEvent("payment_completed", { product: props.productSlug, provider: "mock" }); router.push(`/payment/success?order=${encodeURIComponent(data.orderReference)}&report=${data.reportId}&token=${encodeURIComponent(data.reportToken)}`); return; } await loadRazorpay(); if (!window.Razorpay) throw new Error("Secure payment window could not load."); const checkout = new window.Razorpay({ key: order.keyId, amount: order.amountPaise, currency: order.currency, name: order.name, description: order.description, order_id: order.providerOrderId, prefill: { name: props.customerName, contact: props.customerMobile.replace("+91", "") }, theme: { color: "#0c9368" }, modal: { ondismiss: () => { setBusy(false); } }, handler: async (payment: Record<string, string>) => { const verifyResponse = await fetch("/api/payments/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ internalOrderId: order.internalOrderId, ...payment }) }); const verified = await verifyResponse.json(); if (!verifyResponse.ok) { setError(verified.error || "Payment verification failed."); setBusy(false); return; } trackEvent("payment_completed", { product: props.productSlug, provider: "razorpay" }); router.push(`/payment/success?order=${encodeURIComponent(verified.orderReference)}&report=${verified.reportId}&token=${encodeURIComponent(verified.reportToken)}`); } }); checkout.on("payment.failed", (response) => { router.push(`/payment/failed?assessment=${props.assessmentId}&product=${props.productSlug}&token=${encodeURIComponent(props.resultToken)}&reason=${encodeURIComponent(response.error?.description || "Payment could not be completed")}`); }); checkout.open(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to start payment."); setBusy(false); } }
  return <div className="grid gap-6 lg:grid-cols-[1fr_0.75fr]"><div className="rounded-3xl border border-line bg-white p-6 shadow-card sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-brand-700">Selected product</p><h1 className="mt-3 text-2xl font-bold tracking-[-0.03em] text-navy-950">{props.productName}</h1></div><ShieldCheck className="shrink-0 text-brand-700" /></div><div className="mt-7 grid gap-3 rounded-2xl bg-surface p-5 text-sm"><Price label="Report price" value={props.subtotal} /><Price label="GST (18%)" value={props.gst} /><div className="border-t border-line pt-3"><Price label="Total payable" value={props.total} strong /></div></div><div className="mt-6 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-7 text-amber-950"><CircleAlert className="mt-1 shrink-0" size={19} />{PAYMENT_DESCRIPTION}</div>{error ? <p className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800" role="alert">{error}</p> : null}<Button size="lg" className="mt-6 w-full" onClick={pay} disabled={busy}>{busy ? <Loader2 className="animate-spin" size={18} /> : <LockKeyhole size={18} />}{busy ? "Opening secure checkout…" : `Pay ${props.total} securely`}</Button><p className="mt-4 text-center text-xs leading-5 text-slate-500">Payment order is created server-side. Secret keys never enter the browser.</p></div><aside className="rounded-3xl bg-navy-950 p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-brand-500">Before you pay</p><div className="mt-6 grid gap-4">{["Personalized report prepared from your assessment", "Downloadable branded PDF", "Secure report link with expiry", "Duplicate-payment and system-failure refund coverage"].map((item) => <p key={item} className="flex gap-3 text-sm leading-6 text-slate-300"><Check className="mt-0.5 shrink-0 text-brand-500" size={17} />{item}</p>)}</div><p className="mt-8 border-t border-white/10 pt-6 text-xs leading-6 text-slate-400">{PLATFORM_DISCLAIMER}</p></aside></div>;
}

function Price({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <div className="flex items-center justify-between gap-4"><span className={strong ? "font-bold text-navy-950" : "text-slate-600"}>{label}</span><span className={strong ? "text-lg font-extrabold text-navy-950" : "font-semibold text-navy-950"}>{value}</span></div>; }
async function loadRazorpay() { if (window.Razorpay) return; await new Promise<void>((resolve, reject) => { const script = document.createElement("script"); script.src = "https://checkout.razorpay.com/v1/checkout.js"; script.async = true; script.onload = () => resolve(); script.onerror = () => reject(new Error("Unable to load Razorpay checkout.")); document.head.appendChild(script); }); }
