import { CircleAlert, FileText, LockKeyhole, MessageCircle, ShieldCheck } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";
import { CREDIT_REPORT_DISCLAIMER, PAYMENT_DESCRIPTION, PLATFORM_DISCLAIMER } from "@/lib/constants";

type Props = { kind: "credit" | "readiness"; title: string; heading: string; description: string; regular: string; price: string; total: string; badge: string; deliverables: string[] };

export function ProductPage({ kind, title, heading, description, regular, price, total, badge, deliverables }: Props) {
  return (
    <>
      <section className="hero-premium bg-navy-950 py-16 text-white sm:py-24"><div className="page-shell grid items-center gap-12 lg:grid-cols-[1fr_0.72fr]"><div><span className="rounded-full border border-brand-500/30 bg-brand-500/10 px-4 py-2 text-xs font-bold text-brand-100">{badge}</span><p className="mt-7 text-xs font-extrabold uppercase tracking-[0.2em] text-brand-500">{title}</p><h1 className="mt-4 text-balance text-4xl font-extrabold tracking-[-0.05em] sm:text-5xl">{heading}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{description}</p><ButtonLink href="/assessment" size="lg" className="mt-8">Start With Free Profile Check</ButtonLink></div><div className="rounded-[2rem] border border-white/10 bg-white/8 p-4 shadow-2xl backdrop-blur"><div className="rounded-3xl bg-white p-7 text-navy-950 sm:p-8"><FileText className="text-brand-700" size={32} /><p className="mt-6 text-sm text-slate-500 line-through">Regular {regular}</p><p className="mt-1 text-3xl font-black tracking-[-0.04em]">{price}</p><p className="mt-1 text-sm font-bold text-brand-700">{total}</p><div className="mt-6 flex gap-3 rounded-2xl bg-surface p-4 text-xs leading-6 text-slate-600"><LockKeyhole className="shrink-0 text-brand-700" size={17} />Price appears after the free preview and covers assessment/report services only.</div></div></div></div></section>
      <section className="section-space bg-white"><div className="page-shell grid gap-12 lg:grid-cols-[0.68fr_1.32fr]"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-brand-700">What you receive</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-0.045em] text-navy-950 sm:text-4xl">Personalized, practical और downloadable</h2><p className="mt-4 text-sm leading-7 text-slate-600">The report is based on your assessment inputs. It is not a generic approval certificate.</p></div><div className="grid gap-3 sm:grid-cols-2">{deliverables.map((item, index) => <div key={item} className="flex gap-3 rounded-2xl bg-surface p-5 text-sm font-semibold leading-6 text-navy-900"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-brand-100 text-xs font-black text-brand-700">{index + 1}</span>{item}</div>)}</div></div></section>
      <section className="surface-grid bg-surface py-16"><div className="page-shell grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-line bg-white p-7 shadow-sm"><ShieldCheck className="text-brand-700" /><h2 className="mt-5 text-xl font-extrabold text-navy-950">Payment purpose</h2><p className="mt-3 text-sm leading-7 text-slate-600">{PAYMENT_DESCRIPTION}</p></div><div className="rounded-3xl border border-amber-200 bg-amber-50 p-7"><CircleAlert className="text-amber-700" /><h2 className="mt-5 text-xl font-extrabold text-amber-950">Important boundary</h2><p className="mt-3 text-sm leading-7 text-amber-950">{kind === "credit" ? CREDIT_REPORT_DISCLAIMER : PLATFORM_DISCLAIMER}</p></div></div></section>
      <section className="section-space bg-white"><div className="page-shell flex flex-col items-center rounded-[2rem] bg-brand-100 p-8 text-center sm:p-12"><MessageCircle className="text-brand-700" size={30} /><h2 className="mt-5 text-3xl font-extrabold tracking-[-0.045em] text-navy-950">पहले free profile preview देखें</h2><p className="mt-3 max-w-xl text-sm leading-7 text-slate-600">Choose an optional paid report only after your free result. There is no loan approval or score-increase guarantee.</p><ButtonLink href="/assessment" size="lg" className="mt-7">Start Free Assessment</ButtonLink></div></section>
    </>
  );
}
