import { CircleAlert, FileText, LockKeyhole, MessageCircle, ShieldCheck } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";
import { CREDIT_REPORT_DISCLAIMER, PAYMENT_DESCRIPTION, PLATFORM_DISCLAIMER } from "@/lib/constants";

type Props = { kind: "credit" | "readiness"; title: string; heading: string; description: string; regular: string; price: string; total: string; badge: string; deliverables: string[] };

export function ProductPage({ kind, title, heading, description, regular, price, total, badge, deliverables }: Props) {
  return (
    <>
      <section className="bg-navy-950 py-16 text-white sm:py-24"><div className="page-shell grid items-center gap-12 lg:grid-cols-[1fr_0.75fr]"><div><span className="rounded-full border border-brand-500/30 bg-brand-500/10 px-4 py-2 text-xs font-bold text-brand-100">{badge}</span><p className="mt-7 text-xs font-bold uppercase tracking-[0.18em] text-brand-500">{title}</p><h1 className="mt-4 text-balance text-4xl font-bold tracking-[-0.045em] sm:text-5xl">{heading}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">{description}</p><ButtonLink href="/assessment" size="lg" className="mt-8">Start with free profile check</ButtonLink></div><div className="rounded-3xl border border-white/10 bg-white/7 p-5 backdrop-blur"><div className="rounded-2xl bg-white p-7 text-navy-950"><FileText className="text-brand-700" size={32} /><p className="mt-6 text-sm text-slate-500 line-through">Regular {regular}</p><p className="mt-1 text-3xl font-black tracking-[-0.04em]">{price}</p><p className="mt-1 text-sm font-semibold text-brand-700">{total}</p><div className="mt-6 flex gap-3 rounded-xl bg-surface p-4 text-xs leading-5 text-slate-600"><LockKeyhole className="shrink-0 text-brand-700" size={17} />Price appears after the free preview and is for assessment/report services only.</div></div></div></div></section>
      <section className="section-space bg-white"><div className="page-shell grid gap-12 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-700">What you receive</p><h2 className="mt-3 text-3xl font-bold tracking-[-0.04em] text-navy-950">Personalized, practical और downloadable</h2><p className="mt-4 text-sm leading-7 text-slate-600">Report आपके assessment inputs पर आधारित होगा; generic approval certificate नहीं.</p></div><div className="grid gap-3 sm:grid-cols-2">{deliverables.map((item, index) => <div key={item} className="flex gap-3 rounded-2xl border border-line bg-surface p-5 text-sm font-semibold leading-6 text-navy-900"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-brand-100 text-xs font-black text-brand-700">{index + 1}</span>{item}</div>)}</div></div></section>
      <section className="bg-surface py-14"><div className="page-shell grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border border-line bg-white p-7"><ShieldCheck className="text-brand-700" /><h2 className="mt-5 text-xl font-bold text-navy-950">Payment purpose</h2><p className="mt-3 text-sm leading-7 text-slate-600">{PAYMENT_DESCRIPTION}</p></div><div className="rounded-3xl border border-amber-200 bg-amber-50 p-7"><CircleAlert className="text-amber-700" /><h2 className="mt-5 text-xl font-bold text-amber-950">Important boundary</h2><p className="mt-3 text-sm leading-7 text-amber-950">{kind === "credit" ? CREDIT_REPORT_DISCLAIMER : PLATFORM_DISCLAIMER}</p></div></div></section>
      <section className="section-space bg-white"><div className="page-shell flex flex-col items-center rounded-3xl bg-brand-100 p-8 text-center sm:p-12"><MessageCircle className="text-brand-700" size={30} /><h2 className="mt-5 text-3xl font-bold tracking-[-0.04em] text-navy-950">पहले free profile preview देखें</h2><p className="mt-3 max-w-xl text-sm leading-7 text-slate-600">उसके बाद ही optional paid report चुनें। कोई loan approval या score increase guarantee नहीं.</p><ButtonLink href="/assessment" size="lg" className="mt-7">Free assessment शुरू करें</ButtonLink></div></section>
    </>
  );
}
