import { PageHeader } from "@/components/ui/primitives";
import { DateOnly, DateTime, EmptyOrTable, JsonBlock, ScrollTable, Td, Th } from "@/components/command/page-kit";
import { requirePermission } from "@/lib/auth/session";
import { prisma } from "@/lib/db";

export default async function WeeklyReportsPage() {
  await requirePermission("analytics:view");
  const reports = await prisma.weeklyReport.findMany({ orderBy: { weekStart: "desc" }, take: 52 });
  return (
    <div className="space-y-6">
      <PageHeader title="Weekly reports" description="Stored weekly summaries and action plans." />
      <EmptyOrTable count={reports.length} title="No weekly reports" description="WeeklyReport rows will appear here once generated by AI tooling or scheduled jobs.">
        <ScrollTable>
          <thead><tr><Th>Week start</Th><Th>Summary</Th><Th>Action plan</Th><Th>Delivered</Th><Th>Payload</Th></tr></thead>
          <tbody className="divide-y divide-line">
            {reports.map((report) => (
              <tr key={report.id}>
                <Td><DateOnly value={report.weekStart} /></Td>
                <Td className="max-w-md whitespace-normal">{report.summary}</Td>
                <Td className="max-w-md whitespace-normal">{report.actionPlan ?? "-"}</Td>
                <Td><DateTime value={report.deliveredAt} /></Td>
                <Td className="min-w-80"><JsonBlock value={report.payload} /></Td>
              </tr>
            ))}
          </tbody>
        </ScrollTable>
      </EmptyOrTable>
    </div>
  );
}
